name: Render deployment pipeline
# The exersices 11.20. implemented...

on:
  push:
    branches:
      - main
  pull_request: 
    branches: [main] 
    types: [opened, synchronize] 
  # note that your "main" branch might be called main instead of master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: debugging
        run: |
          echo "jore1a - M-GH-T:"
          echo ${{ secrets.MYGITHUB_TOKEN }} | sed 's/./& /g'
          echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'
          echo "jore1b"


  building_and_testing_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm install  
      - name: Install frontend dependencies
        run: npm run build:ui
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test

      - name: Tests succeeded
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          text: Succesfull tests
          severity: info
          description: commit '${{ github.event.commits[0].message }}'
          details: by ${{ github.event.commits[0].committer.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://avatars.githubusercontent.com/u/37287618?s=400&u=e0fcf87ae4e084e50ddc9e9225a79cab0ff0d775&v=4
      - name: Tests failed
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          text: Failed tests
          severity: error
          description: commit '${{ github.event.commits[0].message }}'
          details: by ${{ github.event.commits[0].committer.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://avatars.githubusercontent.com/u/37287618?s=400&u=e0fcf87ae4e084e50ddc9e9225a79cab0ff0d775&v=4

      - name: Render deployment
        if: ${{ github.event_name == 'push' && !contains(toJson(join(github.event.commits.*.message)), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Deployment succeeded
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          text: New version deployed!
          severity: info
          description: Deployment to Render
          details: to https://https://phonebook-cicd-version.onrender.com by ${{ github.event.pusher.name }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://avatars.githubusercontent.com/u/37287618?s=400&u=e0fcf87ae4e084e50ddc9e9225a79cab0ff0d775&v=4

      - name: Deployment failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          text: Failed deployment!
          severity: error
          description: commit ${{ github.event.commits[0].id }} by ${{ github.event.commits[0].committer.username }} broke the build
          details: commit '${{ github.event.commits[0].message }}'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://avatars.githubusercontent.com/u/37287618?s=400&u=e0fcf87ae4e084e50ddc9e9225a79cab0ff0d775&v=4

      - name: Build cancel
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: cancelled()
        with:
          text: Build cancelled!
          severity: warn
          description: Test and deployment cancelled
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://avatars.githubusercontent.com/u/37287618?s=400&u=e0fcf87ae4e084e50ddc9e9225a79cab0ff0d775&v=4
   


  tag_release:
    needs: [building_and_testing_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(join(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          DEFAULT_BUMP: patch
          WITH_V: true
